# Importing Library

In [1]:
import pandas as pd
from nltk.corpus import stopwords  
from nltk.tokenize import word_tokenize
import nltk

# Reading Data

In [2]:
df=pd.read_excel (r'C:\Users\HP\Downloads\data AI\dataset\dataset.xlsx')
df

,Unnamed: 0,NAME,TITLE,PLACE,POST,EXPRIENCE,RESPONSIBILITY,EDUCATION,DEGREE,SKILLS
0,167,Muhammad Ehsan,FinTech | Digital Banking | Mobile Banking...,karÃ¤Âchi sindh pakistan,software quality assurance engineer sqa engine...,1 yr 10 mos 2 yrs 5 mos 11 mos,none,Mohammad Ali Jinnah University Karachi Univers...,master science ms computer software enginee...,software testing life cycle stlc software deve...
1,90,Amir ImamÃ‚Â®,Automation Team Lead at Contour Software,pakistan,lead,none,none,Pakistan Institute of Management Mohammad Ali ...,diploma project management project managemen...,software quality assurance test cases test aut...
2,205,Syed Akbar Raza Zaidi,SQA Specialist (ISTQB and SFC and SFPC Certifi...,pakistan,none,none,none,Mohammad Ali Jinnah University Usman institute...,master degree computer science 318 engineerin...,test cases testing quality assurance software ...
3,139,Qurat Ul Ain,"Always on the lookout for Talent\n""Hiring SAP ...",pakistan,none,Expired\n Apr 2005,none,Institute of Business & Technology - IBT Feder...,master business administration mba human res...,team management recruiting management human re...
4,197,Kashif Amjad,none,pakistan,business \nunited machineries\n event planner ...,6 yrs 2 yrs 3 mos 2 yrs 2 mos 5 yrs 1 mo 2 yrs...,Marketing head,Muhammad Ali Jinnah University,bachelor science bs computer software engine...,technical support textiles requirements analys...
...,...,...,...,...,...,...,...,...,...,...
218,129,Asad kamran,CEO & Co-Founder at Sudoware,pakistan,sudoware\n,3 yrs 10 mos 3 yrs 10 mos 3 yrs 7 mos,none,DHA Suffa University DA SKBZ,bachelor bs cs computer science high school c...,ios java c swift android
219,91,Muhammad Raqeeb Memon,Student at Muhammad Ali Jinnah university,karÃ¤Âchi sindh pakistan,none,none,none,Muhammad Ali Jinnah university,continue bbah,none
220,93,Shahid Ali,Student at Muhammad Ali Jinnah college,lahore punjab pakistan,none,none,none,Muhammad Ali Jinnah college,1st year non medical,none
221,76,Ali Hasan,Student at Muhammad Ali Jinnah,pakistan,none,none,none,Muhammad Ali Jinnah,bscs computer science,none
222,0,ashir khan,Attended muhammad ali jinnah university,pakistan,none,none,none,muhammad ali jinnah university,none,none

In [3]:
df["words"] = df["PLACE"] +" "+ df["TITLE"] +" "+ df["SKILLS"] +" "+ df["DEGREE"] +" "+ df["EDUCATION"] +" "+ df["POST"] +" "+ df["RESPONSIBILITY"]

In [4]:
df['PLACE'].str.replace('[^\w\s]','',regex=True)
df['PLACE']=df['PLACE'].str.lower()
df['POST'].str.replace('[^\w\s]','',regex=True)
df['POST']=df['POST'].str.lower()
df['SKILLS'].str.replace('[^\w\s]','',regex=True)
df['SKILLS']=df['SKILLS'].str.lower()
df['DEGREE'].str.replace('[^\w\s]','',regex=True)
df['DEGREE']=df['DEGREE'].str.lower()
df['words'].str.replace('[^\w\s]','',regex=True)
df['words']=df['words'].str.lower()

In [7]:
stop = set(stopwords.words('english'))
pat = r'\b(?:{})\b'.format('|'.join(stop))
df['PLACE']=df['PLACE'].str.replace(pat, ' ',regex=True)
df['words']=df['words'].str.replace(pat, ' ',regex=True)
df['SKILLS']=df['SKILLS'].str.replace(pat, ' ',regex=True)
df['DEGREE']=df['DEGREE'].str.replace(pat, ' ',regex=True)
df['POST']=df['POST'].str.replace(pat, ' ',regex=True)

In [8]:
import string
def remove_punctuations(df):
    for punctuation in string.punctuation:
        df = df.replace(punctuation, '')
    return df
df["PLACE"] = df['PLACE'].apply(remove_punctuations)
df["SKILLS"] = df['SKILLS'].apply(remove_punctuations)
df["POST"] = df['POST'].apply(remove_punctuations)
df["DEGREE"] = df['DEGREE'].apply(remove_punctuations)
df["words"] = df['words'].apply(remove_punctuations)

In [10]:
df.to_csv("ali.csv")

In [22]:
df1=pd.read_csv ('Data_scientist_job.csv')

In [23]:
df1

                                               words
0  We are looking for a Data Scientist to analyze...

In [24]:
df1['words'].str.replace('[^\w\s]','',regex=True)
df1['words']=df1['words'].str.lower()

In [25]:
stop = set(stopwords.words('english'))
pat = r'\b(?:{})\b'.format('|'.join(stop))
df1['words']=df1['words'].str.replace(pat, ' ',regex=True)

In [31]:
import string
def remove_punctuations(df1):
    for punctuation in string.punctuation:
        df1 = df1.replace(punctuation, '')
    return df1
df1["words"] = df1['words'].apply(remove_punctuations)

In [32]:
df3 = pd.MultiIndex.from_product(
[df["words"], df1["words"]] , names=["WORDS", "JobDescription"]).to_frame(index=False)

In [33]:
df2=pd.concat([df,df3], axis=1)
df2

,Unnamed: 0,NAME,TITLE,PLACE,POST,EXPRIENCE,RESPONSIBILITY,EDUCATION,DEGREE,SKILLS,words,WORDS,JobDescription
0,167,Muhammad Ehsan,FinTech | Digital Banking | Mobile Banking...,karã¤âchi sindh pakistan,software quality assurance engineer sqa engine...,1 yr 10 mos 2 yrs 5 mos 11 mos,none,Mohammad Ali Jinnah University Karachi Univers...,master science ms computer software enginee...,software testing life cycle stlc software deve...,karã¤âchi sindh pakistan fintech digital b...,karã¤âchi sindh pakistan fintech digital b...,looking data scientist analyze large...
1,90,Amir ImamÃ‚Â®,Automation Team Lead at Contour Software,pakistan,lead,none,none,Pakistan Institute of Management Mohammad Ali ...,diploma project management project managemen...,software quality assurance test cases test aut...,pakistan automation team lead contour softwa...,pakistan automation team lead contour softwa...,looking data scientist analyze large...
2,205,Syed Akbar Raza Zaidi,SQA Specialist (ISTQB and SFC and SFPC Certifi...,pakistan,none,none,none,Mohammad Ali Jinnah University Usman institute...,master degree computer science 318 engineerin...,test cases testing quality assurance software ...,pakistan sqa specialist istqb sfc sfpc cer...,pakistan sqa specialist istqb sfc sfpc cer...,looking data scientist analyze large...
3,139,Qurat Ul Ain,"Always on the lookout for Talent\n""Hiring SAP ...",pakistan,none,Expired\n Apr 2005,none,Institute of Business & Technology - IBT Feder...,master business administration mba human res...,team management recruiting management human re...,pakistan always lookout talent\nhiring s...,pakistan always lookout talent\nhiring s...,looking data scientist analyze large...
4,197,Kashif Amjad,none,pakistan,business \nunited machineries\n event planner ...,6 yrs 2 yrs 3 mos 2 yrs 2 mos 5 yrs 1 mo 2 yrs...,Marketing head,Muhammad Ali Jinnah University,bachelor science bs computer software engine...,technical support textiles requirements analys...,pakistan none technical support textiles requi...,pakistan none technical support textiles requi...,looking data scientist analyze large...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,129,Asad kamran,CEO & Co-Founder at Sudoware,pakistan,sudoware\n,3 yrs 10 mos 3 yrs 10 mos 3 yrs 7 mos,none,DHA Suffa University DA SKBZ,bachelor bs cs computer science high school c...,ios java c swift android,pakistan ceo cofounder sudoware ios java c ...,pakistan ceo cofounder sudoware ios java c ...,looking data scientist analyze large...
219,91,Muhammad Raqeeb Memon,Student at Muhammad Ali Jinnah university,karã¤âchi sindh pakistan,none,none,none,Muhammad Ali Jinnah university,continue bbah,none,karã¤âchi sindh pakistan student muhammad a...,karã¤âchi sindh pakistan student muhammad a...,looking data scientist analyze large...
220,93,Shahid Ali,Student at Muhammad Ali Jinnah college,lahore punjab pakistan,none,none,none,Muhammad Ali Jinnah college,1st year non medical,none,lahore punjab pakistan student muhammad ali ...,lahore punjab pakistan student muhammad ali ...,looking data scientist analyze large...
221,76,Ali Hasan,Student at Muhammad Ali Jinnah,pakistan,none,none,none,Muhammad Ali Jinnah,bscs computer science,none,pakistan student muhammad ali jinnah none bs...,pakistan student muhammad ali jinnah none bs...,looking data scientist analyze large...
222,0,ashir khan,Attended muhammad ali jinnah university,pakistan,none,none,none,muhammad ali jinnah university,none,none,pakistan attended muhammad ali jinnah universi...,pakistan attended muhammad ali jinnah universi...,looking data scientist analyze large...

In [34]:
df2=df2.drop(['words'], axis = 1)

In [35]:
df2

,Unnamed: 0,NAME,TITLE,PLACE,POST,EXPRIENCE,RESPONSIBILITY,EDUCATION,DEGREE,SKILLS,WORDS,JobDescription
0,167,Muhammad Ehsan,FinTech | Digital Banking | Mobile Banking...,karã¤âchi sindh pakistan,software quality assurance engineer sqa engine...,1 yr 10 mos 2 yrs 5 mos 11 mos,none,Mohammad Ali Jinnah University Karachi Univers...,master science ms computer software enginee...,software testing life cycle stlc software deve...,karã¤âchi sindh pakistan fintech digital b...,looking data scientist analyze large...
1,90,Amir ImamÃ‚Â®,Automation Team Lead at Contour Software,pakistan,lead,none,none,Pakistan Institute of Management Mohammad Ali ...,diploma project management project managemen...,software quality assurance test cases test aut...,pakistan automation team lead contour softwa...,looking data scientist analyze large...
2,205,Syed Akbar Raza Zaidi,SQA Specialist (ISTQB and SFC and SFPC Certifi...,pakistan,none,none,none,Mohammad Ali Jinnah University Usman institute...,master degree computer science 318 engineerin...,test cases testing quality assurance software ...,pakistan sqa specialist istqb sfc sfpc cer...,looking data scientist analyze large...
3,139,Qurat Ul Ain,"Always on the lookout for Talent\n""Hiring SAP ...",pakistan,none,Expired\n Apr 2005,none,Institute of Business & Technology - IBT Feder...,master business administration mba human res...,team management recruiting management human re...,pakistan always lookout talent\nhiring s...,looking data scientist analyze large...
4,197,Kashif Amjad,none,pakistan,business \nunited machineries\n event planner ...,6 yrs 2 yrs 3 mos 2 yrs 2 mos 5 yrs 1 mo 2 yrs...,Marketing head,Muhammad Ali Jinnah University,bachelor science bs computer software engine...,technical support textiles requirements analys...,pakistan none technical support textiles requi...,looking data scientist analyze large...
...,...,...,...,...,...,...,...,...,...,...,...,...
218,129,Asad kamran,CEO & Co-Founder at Sudoware,pakistan,sudoware\n,3 yrs 10 mos 3 yrs 10 mos 3 yrs 7 mos,none,DHA Suffa University DA SKBZ,bachelor bs cs computer science high school c...,ios java c swift android,pakistan ceo cofounder sudoware ios java c ...,looking data scientist analyze large...
219,91,Muhammad Raqeeb Memon,Student at Muhammad Ali Jinnah university,karã¤âchi sindh pakistan,none,none,none,Muhammad Ali Jinnah university,continue bbah,none,karã¤âchi sindh pakistan student muhammad a...,looking data scientist analyze large...
220,93,Shahid Ali,Student at Muhammad Ali Jinnah college,lahore punjab pakistan,none,none,none,Muhammad Ali Jinnah college,1st year non medical,none,lahore punjab pakistan student muhammad ali ...,looking data scientist analyze large...
221,76,Ali Hasan,Student at Muhammad Ali Jinnah,pakistan,none,none,none,Muhammad Ali Jinnah,bscs computer science,none,pakistan student muhammad ali jinnah none bs...,looking data scientist analyze large...
222,0,ashir khan,Attended muhammad ali jinnah university,pakistan,none,none,none,muhammad ali jinnah university,none,none,pakistan attended muhammad ali jinnah universi...,looking data scientist analyze large...

# Algorithm

In [39]:
import pandas as pd 
from sklearn.metrics.pairwise import cosine_similarity
from similarity.cosine import Cosine
cosine = Cosine(2)
df2["p0"] = df2["WORDS"].apply(lambda s: cosine.get_profile(s)) 
df2["p1"] = df2["JobDescription"].apply(lambda s: cosine.get_profile(s)) 
df2["jn"] = [cosine.similarity_profiles(p0,p1) for p0,p1 in zip(df2["p0"],df2["p1"])]

df2=df2.drop(["p0", "p1"], axis=1)

In [40]:
df2.to_csv("done.csv")
df2

,Unnamed: 0,NAME,TITLE,PLACE,POST,EXPRIENCE,RESPONSIBILITY,EDUCATION,DEGREE,SKILLS,WORDS,JobDescription,jn
0,167,Muhammad Ehsan,FinTech | Digital Banking | Mobile Banking...,karã¤âchi sindh pakistan,software quality assurance engineer sqa engine...,1 yr 10 mos 2 yrs 5 mos 11 mos,none,Mohammad Ali Jinnah University Karachi Univers...,master science ms computer software enginee...,software testing life cycle stlc software deve...,karã¤âchi sindh pakistan fintech digital b...,looking data scientist analyze large...,0.790716
1,90,Amir ImamÃ‚Â®,Automation Team Lead at Contour Software,pakistan,lead,none,none,Pakistan Institute of Management Mohammad Ali ...,diploma project management project managemen...,software quality assurance test cases test aut...,pakistan automation team lead contour softwa...,looking data scientist analyze large...,0.775247
2,205,Syed Akbar Raza Zaidi,SQA Specialist (ISTQB and SFC and SFPC Certifi...,pakistan,none,none,none,Mohammad Ali Jinnah University Usman institute...,master degree computer science 318 engineerin...,test cases testing quality assurance software ...,pakistan sqa specialist istqb sfc sfpc cer...,looking data scientist analyze large...,0.778306
3,139,Qurat Ul Ain,"Always on the lookout for Talent\n""Hiring SAP ...",pakistan,none,Expired\n Apr 2005,none,Institute of Business & Technology - IBT Feder...,master business administration mba human res...,team management recruiting management human re...,pakistan always lookout talent\nhiring s...,looking data scientist analyze large...,0.861025
4,197,Kashif Amjad,none,pakistan,business \nunited machineries\n event planner ...,6 yrs 2 yrs 3 mos 2 yrs 2 mos 5 yrs 1 mo 2 yrs...,Marketing head,Muhammad Ali Jinnah University,bachelor science bs computer software engine...,technical support textiles requirements analys...,pakistan none technical support textiles requi...,looking data scientist analyze large...,0.863631
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,129,Asad kamran,CEO & Co-Founder at Sudoware,pakistan,sudoware\n,3 yrs 10 mos 3 yrs 10 mos 3 yrs 7 mos,none,DHA Suffa University DA SKBZ,bachelor bs cs computer science high school c...,ios java c swift android,pakistan ceo cofounder sudoware ios java c ...,looking data scientist analyze large...,0.473506
219,91,Muhammad Raqeeb Memon,Student at Muhammad Ali Jinnah university,karã¤âchi sindh pakistan,none,none,none,Muhammad Ali Jinnah university,continue bbah,none,karã¤âchi sindh pakistan student muhammad a...,looking data scientist analyze large...,0.486036
220,93,Shahid Ali,Student at Muhammad Ali Jinnah college,lahore punjab pakistan,none,none,none,Muhammad Ali Jinnah college,1st year non medical,none,lahore punjab pakistan student muhammad ali ...,looking data scientist analyze large...,0.470389
221,76,Ali Hasan,Student at Muhammad Ali Jinnah,pakistan,none,none,none,Muhammad Ali Jinnah,bscs computer science,none,pakistan student muhammad ali jinnah none bs...,looking data scientist analyze large...,0.459788
222,0,ashir khan,Attended muhammad ali jinnah university,pakistan,none,none,none,muhammad ali jinnah university,none,none,pakistan attended muhammad ali jinnah universi...,looking data scientist analyze large...,0.439841

# Ranking

In [44]:
df2.sort_values(by=['jn'], ascending=False)

,Unnamed: 0,NAME,TITLE,PLACE,POST,EXPRIENCE,RESPONSIBILITY,EDUCATION,DEGREE,SKILLS,WORDS,JobDescription,jn
58,192,Abdo ghareeb,Data scientist,egypt,public relations,none,none,National Telecommunications Institute (NTI) Co...,big data science postgraduate training data sc...,machine learning sql requirements analysis bus...,egypt data scientist machine learning sql requ...,looking data scientist analyze large...,0.893976
71,43,Maaz Rafique,Associate Artificial Intelligence Engineer at ...,karã¤âchi sindh pakistan,associate artificial intelligence engineer stu...,4 mos 4 mos 10 mos 3 mos,Developing and implementing computer vision al...,Muhammad Ali Jinnah University,bachelor science bs computer software engin...,machine learning deep learning computer vision...,karã¤âchi sindh pakistan associate artificial...,looking data scientist analyze large...,0.879731
129,59,ARVIND KUMAR,Artificial Intelligence Engineer at Optimizia ...,pakistan,artificial intelligence engineer intern,3 mos 6 mos,Developing and implementing computer vision al...,Mohammad Ali Jinnah University Government high...,bachelor science bs computer science fsc pr...,python programming language data analysis data...,pakistan artificial intelligence engineer op...,looking data scientist analyze large...,0.872994
76,206,Sayed A. Omar,Data Scientist | Instructor | Consultant,6th october al jizah egypt,none,none,none,Cairo University Minia University,masterã¢â‚¬â„¢ degree computer science bachel...,data science machine learning big data softwar...,6th october al jizah egypt data scientist i...,looking data scientist analyze large...,0.866076
4,197,Kashif Amjad,none,pakistan,business \nunited machineries\n event planner ...,6 yrs 2 yrs 3 mos 2 yrs 2 mos 5 yrs 1 mo 2 yrs...,Marketing head,Muhammad Ali Jinnah University,bachelor science bs computer software engine...,technical support textiles requirements analys...,pakistan none technical support textiles requi...,looking data scientist analyze large...,0.863631
...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,93,Shahid Ali,Student at Muhammad Ali Jinnah college,lahore punjab pakistan,none,none,none,Muhammad Ali Jinnah college,1st year non medical,none,lahore punjab pakistan student muhammad ali ...,looking data scientist analyze large...,0.470389
208,50,Asad Butt,Web Developer at Ziltex Pvt Ltd,pakistan,web developer web developer web developer,10 mos 1 yr 3 mos 3 mos,none,Muhammad Ali Jinnah University,bachelorã¢â‚¬â„¢ degree computer science,html css php software development web developm...,pakistan web developer ziltex pvt ltd html c...,looking data scientist analyze large...,0.468516
221,76,Ali Hasan,Student at Muhammad Ali Jinnah,pakistan,none,none,none,Muhammad Ali Jinnah,bscs computer science,none,pakistan student muhammad ali jinnah none bs...,looking data scientist analyze large...,0.459788
222,0,ashir khan,Attended muhammad ali jinnah university,pakistan,none,none,none,muhammad ali jinnah university,none,none,pakistan attended muhammad ali jinnah universi...,looking data scientist analyze large...,0.439841
217,84,Contegris HRD,HR,lahore district punjab pakistan,human resources department,9 yrs 2 mos,none,none,none,none,lahore district punjab pakistan hr none none n...,looking data scientist analyze large...,0.405404

# Happy Ending